### PR TITLE
Update to use qb-target and polyzone

### PR DESCRIPTION
**Pull request by deandum**
To enable qb-target go to config.lua and change `UseTarget`

### CODE REVIEW

**Comment by trclassic92** [comment]
_A few issues I've noticed are._

-  Citizen. (can be removed)

- AddHandlerEvent (can be removed as well)

**Before** 
```
RegisterNetEvent('QBCore:Client:OnPlayerLoaded')
AddEventHandler('QBCore:Client:OnPlayerLoaded', function()
    PlayerData = QBCore.Functions.GetPlayerData()
    QBCore.Functions.TriggerCallback('qb-traphouse:server:GetTraphousesData', function(trappies)
        Config.TrapHouses = trappies
    end)
end)
```

**After**
```
RegisterNetEvent('QBCore:Client:OnPlayerLoaded', function()
    PlayerData = QBCore.Functions.GetPlayerData()
    QBCore.Functions.TriggerCallback('qb-traphouse:server:GetTraphousesData', function(trappies)
        Config.TrapHouses = trappies
    end)
end)
```

Also, the target feature works but while using ( Config.UseTarget = true) the target disables the feature for "keyholders" to be able to use the trap house which then gives everyone access to it. No matter if they are placed as a Keyholder or not in the config.

Meanwhile, if you turn Config.UseTarget = false then you have to place keyholders in the config to be able to use it.

**Comment by deandum** [comment]
> _A few issues I've noticed are._
> 
> * Citizen. (can be removed)
> * AddHandlerEvent (can be removed as well)
> 
> **Before**
> 
> ```
> RegisterNetEvent('QBCore:Client:OnPlayerLoaded')
> AddEventHandler('QBCore:Client:OnPlayerLoaded', function()
>     PlayerData = QBCore.Functions.GetPlayerData()
>     QBCore.Functions.TriggerCallback('qb-traphouse:server:GetTraphousesData', function(trappies)
>         Config.TrapHouses = trappies
>     end)
> end)
> ```
> 
> **After**
> 
> ```
> RegisterNetEvent('QBCore:Client:OnPlayerLoaded', function()
>     PlayerData = QBCore.Functions.GetPlayerData()
>     QBCore.Functions.TriggerCallback('qb-traphouse:server:GetTraphousesData', function(trappies)
>         Config.TrapHouses = trappies
>     end)
> end)
> ```
> 
> Also, the target feature works but while using ( Config.UseTarget = true) the target disables the feature for "keyholders" to be able to use the trap house which then gives everyone access to it. No matter if they are placed as a Keyholder or not in the config.
> 
> Meanwhile, if you turn Config.UseTarget = false then you have to place keyholders in the config to be able to use it.

I noticed the issues you are describing. However, that is outside of the scope of what we are trying to do with this update. That being said, I might just leave those in there and log a different issue to refactor them.

I will take a look at the permissions. The `UseTarget` config should just enable the menus to trigger actions. There are no uddates that change the actual behavior of the traphouse.

**Comment by trclassic92** [comment]
The only other thing I really saw just a minute ago is `DrawText3Ds` is being changed to `exports['qb-core']:DrawText('text', 'placement')`

**Comment by trclassic92** [comment]
Also `DrawText3Ds` is being changed to `exports['qb-core']:DrawText('message', 'left')`

**Comment by deandum** [comment]
> Also `DrawText3Ds` is being changed to `exports['qb-core']:DrawText('message', 'left')` (without distance checks)

I am pretty sure this is on a dev branch and not the main/master build. So I don't really want to use it until it's merged.

**Pull request merged**
