### PR TITLE
Changed PIN handling

### PR DESCRIPTION
**Pull request by elpouletorange**
Client would get the default PIN on connect.
I changed it so it is random, and the client ask the server for the good PIN

### CODE REVIEW

**Comment by tom-osborne** [comment]
This is a nice idea, but the PR is not yet ready to be merged.

There are a number of comments left in the PR that should be removed before merging.

You should also include a method for developers or admins to get the current pin code through a command as currently there would be no way to know what the pin code is without getting a sticky note from an NPC. I think your comments may have been an attempt at this, but a working example should be included in the PR.

**Comment by elpouletorange** [comment]
I updated the code so it is more clear.
Added a /showpin command for admin

**Comment by elpouletorange** [comment]
I agree with you about the percentage thing. I wanted precision for luck. eg 2.5%. = 25/1000. Could change that for it to be 1/x. eg 1/40

**Comment by AnishBplayz** [comment]
Sure it seems a good PR to me.. Tag me once its ready to be reviewed

**Pull request closed without merging**
